web:
  build: .
  command: develop
  volumes:
    - .:/rw_chart
  ports:
    - '3040:3040'
  links:
    - postgres
    - redis
  env_file: dev.env

postgres:
  image: postgres
  container_name: postgres_rw_chart

redis:
  image: redis
  container_name: redis_rw_chart
